update process check

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -5,10 +5,36 @@ source $OPENSHIFT_CARTRIDGE_SDK_BASH
 STOPTIMEOUT=10
 FMT="%a %b %d %Y %H:%M:%S GMT%z (%Z)"
 
+ALINOUS_PID_FILE="${OPENSHIFT_ALINOUS_DIR}/run/alinous.pid"
+
+# Kill the process given by $1 and its children
+killtree() {
+    local _pid=$1
+    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
+        killtree ${_child}
+    done
+    echo kill -9 ${_pid}
+    kill -9 ${_pid}
+}
 
 function status() {
     echo "status()"
     
+}
+
+# Check if the tomcatas process is running
+isrunning() {
+    # Check for running app
+    if [ -f "$ALINOUS_PID_FILE" ]; then
+      jbpid=$(cat $ALINOUS_PID_FILE);
+      running=`/bin/ps --no-headers --pid $jbpid`
+      if test -n "$running";
+      then
+        return 0
+      fi
+    fi
+    # not running
+    return 1
 }
 
 
@@ -20,14 +46,24 @@ function start() {
     
     SHELL_DIR=${OPENSHIFT_ALINOUS_DIR}tomcat/bin
     client_message "SHELL_DIR : $SHELL_DIR";
-    ${SHELL_DIR}/startup.sh
-
-   
+    ${SHELL_DIR}/startup.sh > ${OPENSHIFT_ALINOUS_DIR}/logs/tomcat.log 2>&1 &
+    PROCESS_ID=$!
+    
+    echo $PROCESS_ID > $ALINOUS_PID_FILE
+    client_message "PROCESS_ID ---> $PROCESS_ID";
 }
 
 function stop() {
     client_message "Stop tomcat and alinous server";
-    
+    if ! isrunning; then
+        echo "The alinous cartridge is already stopped" 1>&2
+    elif [ -f "$TOMCAT_PID_FILE" ]; then
+        pid=$(cat $TOMCAT_PID_FILE);
+        echo "Sending SIGTERM to tomcat:$pid ..." 1>&2
+        killtree $pid
+    else 
+        echo "Failed to locate ALINOUS PID File" 1>&2
+    fi
     
     exit 0
 }
